### ISSUE TITLE
1.8 Dev Tracking

### ISSUE THREAD

**Issue by automactic** [kiwix/iOS#33]
### Localized Strings
- [x] Library
- [ ] Alerts

### Library
- [x] re-associate session when background download finish
- [x] notification permission when refresh library for the first time
- [x] book detail, add actions
- [x] empty table backgrounds
- [ ] extensive testing downloading System

### Alerts
- [x] Copy URL Alert
- [x] Encapsulate lang filter alert and defer them if lib is not on screen
- [ ] Rate me alert, with Reachability check
